PR #3 - CloudFormation Template
tachOrg/Real-Time-Data-Processing-Application pull request #9
Opened 2023-02-14 03:26 UTC by XrosHeart05

Pull request #3 - Added Cloud Formation template

2023-02-14 03:31 UTC, tacho090 commented on resources/templates/rt_aws_cf_template.yaml
> +  CognitoIdentityPool:
delete cognito pool since we're not using it now

2023-03-02 04:36 UTC, tacho090 requested changes

2023-03-02 04:36 UTC, tacho090 commented on resources/templates/rt_aws_cf_template.yaml
> +Description: "This stack will create the needs to run the real time processing data environment"
```suggestion
Description: "This stack creates the resources to run the real time processing data application"
```

2023-03-02 04:36 UTC, tacho090 commented on resources/templates/rt_aws_cf_template.yaml
> +          // insertIntoDB();
delete commented code

2023-03-04 01:54 UTC, XrosHeart05 commented on resources/templates/rt_aws_cf_template.yaml
> +          // insertIntoDB();
Comment code deleted

2023-03-04 01:56 UTC, XrosHeart05 commented on resources/templates/rt_aws_cf_template.yaml
> +Description: "This stack will create the needs to run the real time processing data environment"
Changes applied

2023-05-02 01:23 UTC, tacho090 approved these changes

2023-05-02 01:23 UTC, merged